# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"

  config.vm.provision "shell", path: "puppet-bootstrap.sh" 
  config.vm.provision "shell", path: "puppet-modules.sh"
  config.vm.provision "puppet" 

  config.vm.provider "aws" do |aws, override|
    config.vm.box = "dummy"
    aws.access_key_id =     ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name =      ENV['AWS_KEYPAIR_NAME']

    aws.ami = "ami-864d84ee"
    aws.instance_type = "t2.micro"

    aws.tags = { 'Name' => 'LibraryCloud SDK'}
    aws.security_groups = [ 'vagrant' ]
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['AWS_PRIVATE_AWS_SSH_KEY_PATH']
  end

end
